# Generated by gallery/generate.py; do not edit.
function rftoolsutility_gallery:clear
# default-analog: Analog default block
setblock 162 100 163 rftoolsutility:analog
# default-counter: Counter default block
setblock 165 100 163 rftoolsutility:counter
# default-crafter1: Crafter Tier 1 default block
setblock 168 100 163 rftoolsutility:crafter1
# default-crafter2: Crafter Tier 2 default block
setblock 171 100 163 rftoolsutility:crafter2
# default-crafter3: Crafter Tier 3 default block
setblock 174 100 163 rftoolsutility:crafter3
# default-creative-screen: Creative Screen default block
setblock 177 100 163 rftoolsutility:creative_screen
# default-destination-analyzer: Destination Analyzer default block
setblock 180 100 163 rftoolsutility:destination_analyzer
# default-dialing-device: Dialing Device default block
setblock 183 100 163 rftoolsutility:dialing_device
# default-digit: Digit default block
setblock 186 100 163 rftoolsutility:digit
# default-environmental-controller: Environmental Controller default block
setblock 162 100 167 rftoolsutility:environmental_controller
# default-invchecker: Inventory Checker default block
setblock 165 100 167 rftoolsutility:invchecker
# default-logic: Logic default block
setblock 168 100 167 rftoolsutility:logic
# default-matter-beamer: Matter Beamer default block
setblock 171 100 167 rftoolsutility:matter_beamer
# default-matter-booster: Matter Booster default block
setblock 174 100 167 rftoolsutility:matter_booster
# default-matter-receiver: Matter Receiver default block
setblock 177 100 167 rftoolsutility:matter_receiver
# default-matter-transmitter: Matter Transmitter default block
setblock 180 100 167 rftoolsutility:matter_transmitter
# default-redstone-receiver: Redstone Receiver default block
setblock 183 100 167 rftoolsutility:redstone_receiver
# default-redstone-transmitter: Redstone Transmitter default block
setblock 186 100 167 rftoolsutility:redstone_transmitter
# default-screen: Screen default block
setblock 162 100 171 rftoolsutility:screen
# default-screen-controller: Screen Controller default block
setblock 165 100 171 rftoolsutility:screen_controller
# default-sensor: Sensor default block
setblock 168 100 171 rftoolsutility:sensor
# default-sequencer: Sequencer default block
setblock 171 100 171 rftoolsutility:sequencer
# default-simple-dialer: Simple Dialer default block
setblock 174 100 171 rftoolsutility:simple_dialer
# default-spawner: Spawner default block
setblock 177 100 171 rftoolsutility:spawner
# default-tank: Tank default block
setblock 180 100 171 rftoolsutility:tank
# default-timer: Timer default block
setblock 183 100 171 rftoolsutility:timer
# default-wire: Wire default block
setblock 186 100 171 rftoolsutility:wire
# tank-cluster-base: Tank cluster base
setblock 162 100 176 rftoolsutility:tank
# tank-cluster-east: Tank cluster east neighbor
setblock 163 100 176 rftoolsutility:tank
# tank-cluster-above: Tank cluster upper neighbor
setblock 162 101 176 rftoolsutility:tank
# stock-control: Stone stock rendering control
setblock 168 100 176 minecraft:stone
function rftoolsutility_gallery:verify
